# Business Data Processor - Docker Compose設定
version: '3.8'

services:
  business-data-processor:
    build:
      context: .
      dockerfile: Dockerfile
    image: business-data-processor:v2.1.0-docker
    container_name: business-data-processor
    hostname: bdp-app
    
    # 起動コマンドの明示的指定（権限問題対策）
    command: ["python", "-m", "streamlit", "run", "app.py", "--server.maxUploadSize", "100"]
    
    # ポート設定
    ports:
      - "8501:8501"
    
    # ボリュームマウント設定（データ永続化）
    volumes:
      # アプリケーションコードをマウント（git pullで即反映）
      - ./:/app:ro
      # アップロードファイル保存用
      - ./data:/app/data:rw
      # ダウンロードファイル保存用  
      - ./downloads:/app/downloads:rw
      # ログファイル保存用
      - ./logs:/app/logs:rw
    
    # 環境変数設定（日本語環境・最適化）
    environment:
      # 日本語設定
      - LANG=ja_JP.UTF-8
      - LC_ALL=ja_JP.UTF-8
      - LC_CTYPE=ja_JP.UTF-8
      - PYTHONIOENCODING=utf-8
      # Streamlit設定
      - STREAMLIT_SERVER_HEADLESS=true
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      # アプリケーション設定
      - APP_VERSION=2.1.0-docker
      - TZ=Asia/Tokyo
    
    # 再起動ポリシー
    restart: unless-stopped
    
    # リソース制限（必要に応じて調整）
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    
    # ヘルスチェック設定
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    
    # ネットワーク設定
    networks:
      - bdp-network

# カスタムネットワーク定義
networks:
  bdp-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16